image: node:latest
before_script:

deploy:
  stage: deploy-website
  script:
    - cd website
    - npm i -g firebase-tools
    - npm install
    - npm run build
    - cp -r static/* public/
    - firebase deploy --only hosting --token $FIREBASE_TOKEN -P "rahneil-n3-co"
  only:
    refs:
      - main
lint:
  stage: test
  script:
    - npm install -g svelte-check
    - svelte-check website
stages:
- test
- deploy