image: node:latest
before_script:
  - npm i -g firebase-tools
deploy-functions:
  stage: deploy
  script:
    - npm run build
    - cp -r static/* public/
    - firebase deploy --only hosting --token $FIREBASE_TOKEN -P "rahneil-n3-co"
  only:
    refs:
      - main
stages:
- test
- deploy
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml