image: node:latest
before_script:
  - cd website
  - npm i -g firebase-tools
  - npm install
deploy:
  stage: deploy
  script:
    - npm run build
    - mkdir -p public
    - cp -r static/* public/
    - firebase deploy --only hosting --token $FIREBASE_TOKEN -P "rahneil-n3-co"
  only:
    refs:
      - main
lint:
  stage: test
  script:
    - npm install -g svelte-check
    - svelte-check .
stages:
- test
- deploy